version: '3.3'

services:
  postgres:
    image: postgres
    container_name: dbfila
    env_file: ./.env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_ROOT_PASSWORD
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    networks:
      - fila_default

  app:
    depends_on:
      - postgres
    build: ./
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://postgres:$POSTGRES_DOCKER_PORT/$POSTGRES_DATABASE",
        "spring.datasource.username" : "$POSTGRES_ROOT_USER",
        "spring.datasource.password" : "$POSTGRES_ROOT_PASSWORD",
        "spring.jpa.hibernate.show-sql" : true,
        "spring.datasource.initialization-mode" : "always",
        "spring.datasource.initialize" : true,
        "spring.datasource.continue-on-error": true,
        "spring.jpa.hibernate.ddl-auto":"update",
        "server.port" : "$SPRING_LOCAL_PORT"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - fila_default

  phppgadmin:
    image: dpage/pgadmin4
    container_name: phppgadminfila
    env_file: ./.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_ROOT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_ROOT_PASSWORD
    ports:
      - "8080:80"
    networks:
      - fila_default

networks:
  fila_default:
    driver: bridge
