# Create a configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: apl-fila-config
  labels:
    app: apl-fila
data:
  DATASOURCE_INITIALIZATION_MODE: always
  DATASOURCE_INITIALIZE: 'true'
  DATASOURCE_CONTINUE_ON_ERROR: 'true'
  HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
  HIBERNATE_SHOW_SQL: 'true'
  HIBERNATE_DDL_AUTO: update
  SERVER_PORT: '9092'
  PEDIDO_URL: http://acd652e434c7140808cb5801d25eea90-928075136.us-east-1.elb.amazonaws.com:9091/tech-challenge/pedidos
  SERVLET_CONTEXT_PATH: /tech-challenge
  FEIGN_CONNECT_TIMEOUT: '14000'
  FEIGN_READ_TIMEOUT: '14000'
  SPRING_DB_URL: jdbc:postgresql://fila-database.cbl56l2toixh.us-east-1.rds.amazonaws.com:5432/postgres?ssl=true&sslmode=require&rejectUnauthorized=false
  SPRING_DB_USER: postgres
  SPRING_DB_PASS: postgres